### ISSUE TITLE
FREX

### ISSUE THREAD

**Issue by machinesmith42** [ReMod-Studios/flaring-abyss-bedrock#1]
FREX

**Comment by YuRaNnNzZZ** [comment]
![:help_me:](https://cdn.discordapp.com/emojis/757677695441174598.png?v=1)

**Comment by LePichu** [comment]
Sir we use Bedrock Rendering Extensions down here, not Fabric/Forge Rendering Extensions. For suggesting use, go to the Fabric/Forge repository, not this Bedrock one.

**Comment by GiantLuigi4** [comment]
Frex

**Comment by Minerrr** [comment]
yo mama

**Comment by sylv256** [comment]
FREX
![help_me](https://camo.githubusercontent.com/c6995b14866bf2bb08393fc6909ef7dfb435a020d308511805a289a0b268b917/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3735373637373639353434313137343539382e706e673f763d31)

**Comment by machinesmith42** [comment]
FREX
